#!/bin/bash

app=framagames

#user=$(sudo yunohost app setting $app user)
path=$(sudo yunohost app setting $app path)
sitename=$(sudo yunohost app setting $app sitename)
domain=$(sudo yunohost app setting $app domain)
final_path=$(sudo yunohost app setting $app final_path)


# Suppression du dossier de la webapp
sudo rm -rf $final_path

# Suppression de la config nginx de la webapp
sudo rm -f /etc/nginx/conf.d/$domain.d/$sitename.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
sudo rm -rf /var/www/$app/

sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf
